//created on: Jun 18, 2020
package defencefirst.rules;

//list any import classes here.
import rs.ac.uns.ftn.siemcentar.model.Log;
import rs.ac.uns.ftn.siemcentar.model.LogType;
import rs.ac.uns.ftn.siemcentar.model.Alarm;
import java.util.Date;
//declare any global variables here

rule "Your First Rule"
    when
        $log: Log(processed == false, logType == LogType.ERROR)
    then
        modify($log){setProcessed(true)}
        insert(new Alarm(null, new Date(), "Log tipa error"));
end
